### ISSUE TITLE
Allow directives to respect significant whitespace

### ISSUE THREAD

**Issue by trezy** [remarkjs/remark-directive#1]
### Subject of the feature

Generic directives, particularly container directives, currently assume that leading whitespace should be removed. This is a sensible assumption in many cases, but for generic directives, it would be valuable to keep significant whitespace. I'd like to propose that an option be added to this plugin that allows directives to respect (or not) significant whitespace.

### Problem

This problem manifests when using generic directives for content that requires the use of significant whitespace. For example, I have a directive that renders DITAA ([DIagrams Through ASCII Art](http://ditaa.sourceforge.net/) to an image. The content of the directive is ASCII art, which itself requires significant whitespace to be rendered correctly. For example, consider this usage of directives for a DITAA diagram:

```markdown
:::ditaa
+---+
| A |
+-+-+
  |  +---+
  +->+ B +
     +---+
:::
```

When significant whitespace is respected, it produces this diagram:

![Example of a diagram rendered with DITAA while respecting significant whitespace](https://kroki.io/ditaa/svg/eNrT1tXV1eaqUXBUqOHS1gVCLgWFGgUFbbAwiLbTVnBSADEVoKIA4kEIaA==)

However, this is the result when significant whitespace is not respected:

![Example of a diagram rendered with DITAA without respecting significant whitespace](https://kroki.io/ditaa/svg/eNrT1tXV1eaqUXBUqOHS1tUGsxW0wYLaunbaCk4KIAaQCwCfpAdI)

### Alternatives

Currently, `remark-directive` allows whitespace to be maintained by wrapping the contents of a directive in code fences, e.g.

````markdown
:::ditaa
```
+---+
| A |
+-+-+
  |  +---+
  +->+ B +
     +---+
```
:::
````

This seems like more of a bug than a feature, but I honestly haven't dug into the code of the plugin yet.

### Reference

I've also brought this up [in the Generic Directive discussion for Commonmark](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444/163).

**Comment by wooorm** [comment]
Hey hey!

I kinda do like the alternative: that’s what I’d suggest; it makes the most sense to me.

Markdown is a whitespace sensitive language: a lot of its constructs care about whether you indented something or not, and how much, and I think generic directives should not change that.

I don’t think I’d be interested in changing this semi-standard directives proposal unless other implementations also change 🤔

**Comment by wooorm** [comment]
Going to close this because it seems the linked thread is not going in the direction of this proposal, similar to my own aforementioned views.
