### ISSUE TITLE
Escaping quotes does not work

### ISSUE THREAD

**Issue by 2manyvcos** [remarkjs/remark-directive#14]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-directive

### Steps to reproduce

It is not possible to escape quotes in attribute, e.g. the following two examples do not work:

```md
:test[content]{a="content with escaped \" quote"}
:test[content]{a='content with escaped \' quote'}
```

The only way to do this currently is to use ASCII codes:

```md
:test[content]{a="content with escaped &#34; quote"}
:test[content]{a='content with escaped &#39; quote'}
```

### Expected behavior

Escape sequences should work for quotes.

### Actual behavior

The directive is not parsed.

**Comment by 2manyvcos** [comment]
Here is a reproduction example:

https://codesandbox.io/p/sandbox/flamboyant-mestorf-n33ptd?file=%2Fsrc%2Fapp.tsx%3A17%2C4

**Comment by wooorm** [comment]
This is intentional. Markdown supports character references in lots of places. It never supports C-style escapes. Therefore, it is logical to support character references and not C-style escapes here, too.

> ASCII codes

That’s not what those are. Those are *character references*, as defined by the CM and HTML specs.

**Comment by 2manyvcos** [comment]
Thank you for the clarification.

Even though I am a bit confused, because there is a section mentioning backslash escapes in the [CommonMark spec](https://spec.commonmark.org/0.30/#backslash-escapes) and it is possible to escape the whole directive by adding a backslash before the colon, like described in https://github.com/remarkjs/remark-directive/issues/5#issuecomment-869131256.

Also, the following is valid Markdown:
```md
[url with \] escape](test)
```

[url with \] escape](test)

**Comment by wooorm** [comment]
Oh that, sorry, I missed what this was about.
I modelled the attributes after how attributes work in HTML.
So also unquoted ones work.
And more character references work than solely in markdown.
This means you can copy/paste things.

**Comment by 2manyvcos** [comment]
Oh, I see now!
Thank you, that clarified it.
