### ISSUE TITLE
Doesn't work with `react-markdown` 6

### ISSUE THREAD

**Issue by IGassmann** [remarkjs/remark-directive#3]
### Subject of the issue

I've upgraded `react-markdown` to version 6 on my repository and did the [necessary modifications](https://github.com/IGassmann/personal-website/commit/13e23280d49c9fc0b34b7b5f77caf72eb7624541) for the [breaking changes](https://github.com/remarkjs/react-markdown/blob/HEAD/changelog.md#600---2021-04-15). After that `remark-directive` stopped working. The previously available `leafDirective` renderer/component stopped being called.

### Your environment

*   **OS**: macOS Big Sur
*   **Packages**: `react-markdown`: `^6.0.0`, `remark-directive`: `^1.0.1`
*   **Env**: `node`: `v12.20.0`, `yarn`: `v1.22.10`

### Steps to reproduce

1. Clone https://github.com/IGassmann/personal-website
2. Checkout commit IGassmann/personal-website@13e23280d49c9fc0b34b7b5f77caf72eb7624541
3. `yarn`
4. `yarn dev`
5. Open http://localhost:3000/post/new-brand

### Expected behavior

Figma iframes are supposed to be rendered thanks to the leave directives.

### Actual behavior

`leaveDirective` renderer/component is never called.

**Comment by ChristianMurphy** [comment]
it does, the new flow is

```
                                                           react-markdown
+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                             |
|            +----------+        +----------------+        +---------------+       +----------------+       +--------------+                  |
|            |          |        |                |        |               |       |                |       |              |                  |
| -markdown->+  remark  +-mdast->+ remark plugins +-mdast->+ remark-rehype +-hast->+ rehype plugins +-hast->+  components  +-react elements-> |
|            |          |        |                |        |               |       |                |       |              |                  |
|            +----------+        +----------------+        +---------------+       +----------------+       +--------------+                  |
|                                                                                                                                             |
+---------------------------------------------------------------------------------------------------------------------------------------------+
```

the custom mdast node needs a plugin to convert it to hast.
There's an example of how to do this in the readme of `remark-directive` (https://github.com/remarkjs/remark-directive#use) with the `htmlDirectives` plugin, which can be used as an example of a `remarkPlugin` for `react-markdown`

**Comment by IGassmann** [comment]
Would you be able to provide an example or more explanation? I've tried the linked example and it didn't work for me.

**Comment by ChristianMurphy** [comment]
Could you share what you tried in a codesandbox?
Using https://codesandbox.io/s/react-markdown-debug-9n4eg as a starting point

**Comment by IGassmann** [comment]
I got it figured out with the following:

```js
import React from "react";
import Markdown from "react-markdown";
import directive from "remark-directive";
import visit from "unist-util-visit";

const markdownSource = `::test{attr='A attribute'}`;

const markdownComponents = {
  textDirective: (directive) => console.log(directive),
  leafDirective: (directive) => console.log(directive),
  containerDirective: (directive) => console.log(directive),
};

function customDirectives() {
  return transform;

  function transform(tree) {
    visit(tree, "textDirective", markdownComponents.textDirective);
    visit(tree, "leafDirective", markdownComponents.leafDirective);
    visit(tree, "containerDirective", markdownComponents.containerDirective);
  }
}

export default function App() {
  return (
    <Markdown
      remarkPlugins={[directive, customDirectives]}
      components={markdownComponents}
    >
      {markdownSource}
    </Markdown>
  );
}
```

However, what is confusing to me is that with the previous version of `react-markdown` I could have just the following and it would work. `customDirectives` wasn't needed. Would you know the reasoning behind this change?

```js
import React from "react";
import Markdown from "react-markdown";
import directive from "remark-directive";

const markdownSource = `::test{attr='A attribute'}`;

const markdownRenderers = {
  textDirective: (directive) => {
    console.log(directive)
    return <a>{directive.name}</a>
  },
  leafDirective: (directive) => {
    console.log(directive)
    return <a>{directive.name}</a>
  },
  containerDirective: (directive) => {
    console.log(directive)
    return <a>{directive.name}</a>
  }
};

export default function App() {
  return (
    <Markdown
      plugins={[directive]}
      renderers={markdownRenderers}
    >
      {markdownSource}
    </Markdown>
  );
}
```

**Comment by ChristianMurphy** [comment]
> Would you know the reasoning behind this change?

The reasoning is explained here https://github.com/remarkjs/react-markdown/issues/427 The other issues linked to that issue add even more context.
The TL;DR the HTML handling in react-markdown was broken and remark plugins (like remark-math, remark-external-links, and remark-slug) rely on being able to set HTML attributes were broken, using remark-rehype resolved both.

**Comment by IGassmann** [comment]
I see. Thanks for the help! :)

**Comment by BrunoQuaresma** [comment]
Just checking. Right now, there is no "direct" way to use remark-directive with react-markdown? Is that right?

**Comment by wooorm** [comment]
Hi. It is fine to use `remark-directive` with modern `react-markdown`.
You are commenting on an issue about `remark-directive` not working with an old version of `react-markdown`, which you are likely not using.
To use `remark-directive` with modern `react-markdown`, follow their readmes. Also feel free to ask a question in a new, thorough, complete, question in Discussions, that’s the best way to get help.

**Comment by IGassmann** [comment]
@BrunoQuaresma you can now use this library: https://github.com/IGassmann/remark-directive-rehype
