### ISSUE TITLE
Custom attributes don't work.

### ISSUE THREAD

**Issue by ivands** [remarkjs/remark-directive#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.1

### Steps to reproduce

Trying to set custom attributes on the element doesn't work
```
data.hName = 'div';
data.hProperties = {
  id: 'something',
  className: 'something',
  class: 'something',
  src: 'something',
};
```

### Expected behavior

```<div id="something" class="something" src="something"><div>```

### Actual behavior

```<div id="user-content-something"><div>```

### Runtime

Node v14

### Package manager

yarn v2

### OS

macOS

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
There’s not enough information provided and, when asked, you did not provide more. Perhaps you’ve already solved it. Closing as this can’t be acted on.
