### ISSUE TITLE
Type Definition doesn't work

### ISSUE THREAD

**Issue by rikusen0335** [remarkjs/remark-directive#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-directive@2.0.1

### Steps to reproduce

This problem is probably not a package issue itself, so I couldn't reproduce.

---

Quick note: I use astro to develop, so I chose vite as a build tools.

### Expected behavior

Getting a type like `visit(tree: Tree, (node: Node) => { ... })` (I'm not sure if these type are correct, just writing for example) and so I can use complenition like `node.name ...`

### Actual behavior

As this image shows, like `visit` function won't show its type.
<img width="577" alt="スクリーンショット 2022-11-29 16 20 24" src="https://user-images.githubusercontent.com/19174234/204465126-4069a1df-c7d7-46a9-844d-bced25da7cc9.png">

### Runtime

Node v16

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment]
Could you share a runnable example of the issue?
The screens hot doesn't offer enough information on what are are trying to achieve.

Some starters:

| description | codesandbox | stackblitz |
| - | - | - |
| remark only (for markdown to markdown) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-with-parcel) |
| remark and rehype (for markdown to html) | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-parcel) |
| react-markdown | [codesandbox](https://codesandbox.io/s/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) | [stackblitz](https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/react-markdown-with-create-react-app) |

---

From what I can gather, you're question is about the visitor types from https://github.com/syntax-tree/unist-util-visit?

And it looks like you are using TypeScript syntax (`.ts` file extension), but annotating it with JSDoc style TypeScript?
Those to don't work together in the same file.
For how to annotate a plugin use something like
```ts
const remarkCustomPlugin: Plugin<[], Root> =
```

(And consider looking through the code of https://github.com/remcohaszing/remark-mdx-images for a more complete TypeScript syntax example)

And for visitors, it may not need an annotation once the plugin is correctly typed.
But if you need to further narrow the type see https://unifiedjs.com/learn/recipe/narrow-node-typescript/

**Comment by rikusen0335** [comment]
Thanks @ChristianMurphy !

I finally figured it out and that was not a problem of this lib as you said.

We need to do like this in `.ts` file:
```ts
import type { Root } from 'remark-directive';
import type { Plugin } from 'unified';

const customComponentRemarkPlugin: Plugin<[], Root> = () => {
  return (tree) => {
    visit(tree, (node) => {
    }
  }
}
```

**Comment by VityaSchel** [comment]
Have you figured out how to extend TypeScript definitions for a custom node? Coming from the [example](https://github.com/remarkjs/remark-directive/?tab=readme-ov-file#example-youtube) provided in README, I figured I need to let TypeScript know that LeafDirective can be either the lib's LeafDirective or my own custom type:

```ts
export interface CustomEmbed extends LeafDirective {
	type: "leafDirective";
	name: "embed";
	attributes?: {
		url?: string;
	};
}
type CustomNodes = CustomEmbed;


export const customDirectives: Plugin<[], Root> = () => {
	return (tree, file) => {
		visit(tree, (node) => {
			if (
				node.type === "textDirective" ||
				node.type === "leafDirective" ||
				node.type === "containerDirective"
			) {
				if (node.name === "embed") {
					if (node.type !== "leafDirective") {
						return file.fail(
							"Unexpected :embed directive type, use two colons for a leaf directive",
							node,
						);
					}

					// 'node.data' is possibly 'undefined'.
					// Property 'hName' does not exist on type 'LeafDirectiveData'
					// How to extend LeafDirectiveData globally to allow "embed" tag?
					node.data.hName = "embed";
					node.data.hProperties = {
						url: node.children[0]?.value || node.attributes?.url,
					};
				}
			}
		});
	};
};

```

**Comment by ChristianMurphy** [comment]
@VityaSchel you don't want to extend the node, you want to narrow it.
https://unifiedjs.com/learn/recipe/narrow-node-typescript/

If you want to force a node to have specific properties, you may also want to use a runtime type parser to narrow like https://zod.dev/
